import { colors, typography } from '@clocktower/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  token: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9999,
    borderWidth: 1,
    // 토큰 내부 미세 질감 — 그라디언트 대신 안쪽 ring 처럼 2차 보더 느낌
  },
  name: {
    fontFamily: typography.family.display,
    color: colors.parchment.high,
    fontSize: 12,
    fontWeight: typography.weight.semibold,
    letterSpacing: typography.tracking.tight,
    textAlign: 'center',
  },
  role: {
    fontFamily: typography.family.body,
    fontSize: 10,
    textAlign: 'center',
    marginTop: 2,
    color: colors.parchment.mid,
  },
  deadStroke: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 2,
    marginTop: 2,
    position: 'absolute',
    bottom: -8,
  },
  statusBadge: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
  },
  statusText: {
    fontFamily: typography.family.body,
    color: '#ffffff',
    fontSize: 8,
    fontWeight: typography.weight.bold,
  },
  voteBadgeText: {
    position: 'absolute',
    top: -8,
    right: -8,
  },
  voteReadyStamp: {
    position: 'absolute',
    top: -10,
    right: -10,
    borderRadius: 9999,
    backgroundColor: colors.verdure.core,
    borderWidth: 2,
    borderColor: colors.verdure.glow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voteReadyCheck: {
    fontFamily: typography.family.body,
    color: colors.parchment.high,
    fontWeight: typography.weight.black,
    lineHeight: 16,
    includeFontPadding: false,
  },
  voteReadyBadge: {
    position: 'absolute',
    bottom: -14,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: colors.verdure.deep,
    borderWidth: 1,
    borderColor: colors.verdure.glow,
    borderRadius: 10,
  },
  voteReadyBadgeText: {
    fontFamily: typography.family.body,
    color: colors.verdure.glow,
    fontWeight: typography.weight.bold,
    letterSpacing: typography.tracking.wide,
  },
  nominationBadge: {
    position: 'absolute',
    top: -6,
    left: -6,
  },
  nominationTargetBadge: {
    position: 'absolute',
    bottom: -6,
    right: -6,
  },
  memoBadge: {
    position: 'absolute',
    bottom: -6,
    left: -6,
  },
  tooltipOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  tooltipBox: {
    backgroundColor: colors.ink.mid,
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 16,
    maxWidth: 280,
  },
  tooltipTitle: {
    fontFamily: typography.family.display,
    fontSize: 14,
    fontWeight: typography.weight.bold,
    marginBottom: 6,
  },
  tooltipDesc: {
    fontFamily: typography.family.body,
    color: colors.parchment.mid,
    fontSize: 13,
    lineHeight: 19,
  },
});
