import { colors, typography } from '@clocktower/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  token: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9999,
    borderWidth: 2,
    overflow: 'visible',
  },
  innerRing: {
    position: 'absolute',
    top: 5,
    right: 5,
    bottom: 5,
    left: 5,
    borderRadius: 9999,
    borderWidth: 1,
    opacity: 0.35,
  },
  name: {
    color: colors.arcane.text.strong,
    fontSize: 12,
    fontFamily: typography.fontFamily.bodyBold,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingHorizontal: 6,
  },
  role: {
    color: colors.arcane.text.muted,
    fontSize: 10,
    fontFamily: typography.fontFamily.bodyMedium,
    textAlign: 'center',
    marginTop: 2,
    paddingHorizontal: 6,
  },
  deadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  dead: {
    color: colors.arcane.action.bloodHighlight,
    fontSize: 10,
    fontFamily: typography.fontFamily.bodyBold,
    fontWeight: 'bold',
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 2,
    marginTop: 2,
    position: 'absolute',
    bottom: -8,
  },
  statusBadge: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: colors.arcane.surface.base,
  },
  statusText: {
    color: colors.arcane.text.strong,
    fontSize: 8,
    fontFamily: typography.fontFamily.bodyBold,
    fontWeight: '700',
  },
  voteBadgeText: {
    position: 'absolute',
    top: -8,
    right: -8,
  },
  nominationBadge: {
    position: 'absolute',
    top: -6,
    left: -6,
  },
  nominationTargetBadge: {
    position: 'absolute',
    bottom: -6,
    right: -6,
  },
  memoBadge: {
    position: 'absolute',
    bottom: -6,
    left: -6,
  },
  tooltipOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(13,7,3,0.82)',
  },
  tooltipBox: {
    backgroundColor: colors.arcane.surface.raised,
    borderWidth: 1.5,
    borderRadius: 6,
    paddingHorizontal: 20,
    paddingVertical: 16,
    maxWidth: 280,
    borderColor: colors.arcane.border.brassDim,
  },
  tooltipTitle: {
    fontSize: 14,
    fontFamily: typography.fontFamily.bodyBold,
    fontWeight: '700',
    marginBottom: 6,
  },
  tooltipDesc: {
    color: colors.arcane.text.primary,
    fontSize: 13,
    fontFamily: typography.fontFamily.body,
    lineHeight: 19,
  },
});
