import { StyleSheet } from 'react-native';

export const COLORS = {
  brass: '#b8964e',
  brassLight: '#d4b06a',
  brassDark: '#8a6e38',
  bloodGlow: '#c43c3c',
  iron: '#4a4a52',
  ironDark: '#2a2a30',
  active: '#e8c44a',
};

export const styles = StyleSheet.create({
  pointerEventsNone: {
    pointerEvents: 'none',
  },
  wedgeContainer: {
    position: 'absolute',
    zIndex: 40,
  },
  outerTriangle: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 0,
    height: 0,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },
  innerTriangle: {
    position: 'absolute',
    bottom: 0,
    width: 0,
    height: 0,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },
  handContainer: {
    position: 'absolute',
    alignItems: 'center',
    zIndex: 50,
  },
  handGlow: {
    position: 'absolute',
    width: 10,
    borderRadius: 5,
    backgroundColor: `${COLORS.bloodGlow}25`,
  },
  hand: {
    position: 'absolute',
    width: 3,
    borderRadius: 2,
    backgroundColor: COLORS.brass,
    shadowColor: COLORS.brassLight,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 5,
  },
  handTip: {
    position: 'absolute',
    top: -5,
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: COLORS.brassLight,
  },
  centerHub: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLORS.ironDark,
    borderWidth: 2,
    borderColor: COLORS.brassDark,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 51,
    shadowColor: COLORS.brass,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
  },
  centerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.brass,
  },
});
