import { colors, typography } from '@clocktower/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.arcane.surface.base,
  },
  backgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  topRule: {
    width: '100%',
    height: 1,
    backgroundColor: colors.arcane.border.brassDim,
    opacity: 0.35,
    marginBottom: 34,
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 34,
  },
  titleSubtext: {
    color: colors.arcane.text.label,
    fontFamily: typography.fontFamily.bodyMedium,
    fontSize: 13,
    letterSpacing: 0,
    marginBottom: 6,
    textShadowColor: 'rgba(141, 53, 41, 0.45)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  titleText: {
    color: colors.arcane.text.strong,
    fontFamily: typography.fontFamily.display,
    fontSize: 58,
    letterSpacing: 0,
    textShadowColor: 'rgba(183, 134, 66, 0.45)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  titleDivider: {
    width: 92,
    height: 1,
    marginTop: 14,
  },
  titleDividerGradient: {
    flex: 1,
    height: 1,
  },
  // Decorative cross marks flanking the title
  decorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 12,
  },
  decorCross: {
    color: colors.arcane.border.brassDim,
    fontSize: 10,
    lineHeight: 16,
  },
  decorCenter: {
    color: colors.arcane.action.bloodHighlight,
    fontSize: 12,
    lineHeight: 16,
    marginHorizontal: 2,
  },
  form: {
    gap: 16,
    padding: 16,
    backgroundColor: 'rgba(38, 22, 6, 0.72)',
    borderWidth: 1,
    borderColor: colors.arcane.border.parchment,
    borderRadius: 6,
  },
  label: {
    color: colors.arcane.text.label,
    fontFamily: typography.fontFamily.bodyMedium,
    fontSize: 12,
    letterSpacing: 0,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    gap: 8,
  },
  input: {
    backgroundColor: colors.arcane.surface.apparatus,
    borderWidth: 1,
    borderColor: colors.arcane.border.brassDim,
    borderRadius: 6,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: colors.arcane.text.primary,
    fontFamily: typography.fontFamily.body,
    fontSize: 16,
  },
  ipInput: {
    flex: 1,
  },
  scanButton: {
    backgroundColor: colors.arcane.surface.apparatus,
    borderWidth: 1,
    borderColor: colors.arcane.border.brassDim,
    borderRadius: 6,
    paddingHorizontal: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanButtonPressed: {
    backgroundColor: colors.arcane.action.bloodPressed,
    borderColor: colors.arcane.action.bloodHighlight,
  },
  scanButtonText: {
    color: colors.arcane.text.label,
    fontFamily: typography.fontFamily.bodyBold,
    fontSize: 13,
    letterSpacing: 0,
  },
  errorText: {
    color: colors.arcane.action.bloodHighlight,
    fontFamily: typography.fontFamily.bodyMedium,
    fontSize: 14,
    textAlign: 'center',
    textShadowColor: 'rgba(200, 50, 50, 0.4)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  joinButton: {
    borderRadius: 6,
    paddingVertical: 16,
    marginTop: 8,
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.arcane.border.brass,
  },
  joinButtonGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  joinButtonPressed: {
    opacity: 0.8,
  },
  joinButtonText: {
    color: colors.arcane.text.strong,
    fontFamily: typography.fontFamily.bodyBold,
    fontSize: 16,
    letterSpacing: 0,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  // Scanner styles (unchanged)
  scannerContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  overlayMask: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 24,
  },
  overlayMiddle: {
    flexDirection: 'row',
  },
  scanArea: {
    width: 240,
    height: 240,
  },
  corner: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderColor: colors.arcane.action.bloodHighlight,
  },
  cornerTL: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopLeftRadius: 4,
  },
  cornerTR: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopRightRadius: 4,
  },
  cornerBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomLeftRadius: 4,
  },
  cornerBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderBottomRightRadius: 4,
  },
  scanHint: {
    color: colors.arcane.text.primary,
    fontFamily: typography.fontFamily.bodyMedium,
    fontSize: 14,
    marginTop: 24,
  },
  scannerClose: {
    position: 'absolute',
    bottom: 60,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 8,
  },
  scannerCloseText: {
    color: colors.arcane.text.primary,
    fontFamily: typography.fontFamily.bodyBold,
    fontSize: 16,
  },
  footerText: {
    color: colors.arcane.text.dead,
    fontFamily: typography.fontFamily.body,
    fontSize: 11,
    textAlign: 'center',
    marginTop: 48,
    letterSpacing: 0,
  },
  tipContainer: {
    alignItems: 'center',
    marginTop: 18,
  },
  copyright: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    color: colors.arcane.text.dead,
    fontFamily: typography.fontFamily.body,
    fontSize: 10,
    textAlign: 'center',
    lineHeight: 16,
    letterSpacing: 0,
    opacity: 0.55,
  },
  bottomRule: {
    width: '100%',
    height: 1,
    backgroundColor: colors.arcane.border.brassDim,
    opacity: 0.28,
    marginTop: 28,
  },
});
