import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0506',
  },
  backgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 48,
  },
  titleSubtext: {
    color: '#a04040',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 8,
    textTransform: 'uppercase',
    marginBottom: 6,
    textShadowColor: 'rgba(160, 40, 40, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  titleText: {
    color: '#e8d8d0',
    fontSize: 52,
    fontWeight: '900',
    letterSpacing: 4,
    textShadowColor: 'rgba(180, 40, 40, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 20,
  },
  titleDivider: {
    width: 80,
    height: 1,
    marginTop: 18,
  },
  titleDividerGradient: {
    flex: 1,
    height: 1,
  },
  // Decorative cross marks flanking the title
  decorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
  },
  decorCross: {
    color: '#5a2020',
    fontSize: 10,
    lineHeight: 16,
  },
  decorCenter: {
    color: '#8b3030',
    fontSize: 14,
    lineHeight: 16,
    marginHorizontal: 2,
  },
  form: {
    gap: 18,
  },
  label: {
    color: '#786058',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 3,
    marginBottom: 8,
    marginLeft: 4,
  },
  row: {
    flexDirection: 'row',
    gap: 8,
  },
  input: {
    backgroundColor: 'rgba(20, 10, 10, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(120, 40, 40, 0.25)',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: '#d8c8c0',
    fontSize: 16,
  },
  ipInput: {
    flex: 1,
  },
  scanButton: {
    backgroundColor: 'rgba(20, 10, 10, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(120, 40, 40, 0.25)',
    borderRadius: 10,
    paddingHorizontal: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanButtonPressed: {
    backgroundColor: 'rgba(100, 30, 30, 0.3)',
    borderColor: 'rgba(160, 50, 50, 0.4)',
  },
  scanButtonText: {
    color: '#8b6060',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
  },
  errorText: {
    color: '#cc4444',
    fontSize: 14,
    textAlign: 'center',
    textShadowColor: 'rgba(200, 50, 50, 0.4)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  joinButton: {
    borderRadius: 10,
    paddingVertical: 16,
    marginTop: 12,
    alignItems: 'center',
    overflow: 'hidden',
  },
  joinButtonGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  joinButtonPressed: {
    opacity: 0.8,
  },
  joinButtonText: {
    color: '#f0e0d8',
    fontWeight: '900',
    fontSize: 16,
    letterSpacing: 4,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  // Scanner styles (unchanged)
  scannerContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  overlayMask: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 24,
  },
  overlayMiddle: {
    flexDirection: 'row',
  },
  scanArea: {
    width: 240,
    height: 240,
  },
  corner: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderColor: '#943c3c',
  },
  cornerTL: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopLeftRadius: 4,
  },
  cornerTR: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopRightRadius: 4,
  },
  cornerBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomLeftRadius: 4,
  },
  cornerBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderBottomRightRadius: 4,
  },
  scanHint: {
    color: '#e0ddd8',
    fontSize: 14,
    marginTop: 24,
  },
  scannerClose: {
    position: 'absolute',
    bottom: 60,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 8,
  },
  scannerCloseText: {
    color: '#e0ddd8',
    fontSize: 16,
    fontWeight: 'bold',
  },
  footerText: {
    color: '#4a3535',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 48,
    letterSpacing: 1,
  },
  copyright: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    color: '#3a2525',
    fontSize: 10,
    textAlign: 'center',
    lineHeight: 16,
    letterSpacing: 1,
  },
});
