import { colors, typography } from '@clocktower/ui';
import { StyleSheet } from 'react-native';

const arcane = colors.arcane;

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(13,7,3,0.82)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  panel: {
    backgroundColor: arcane.surface.apparatus,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: arcane.border.brassDim,
    padding: 24,
    width: '100%',
    maxWidth: 360,
  },
  title: {
    color: arcane.action.bloodHighlight,
    fontSize: 18,
    fontFamily: typography.fontFamily.display,
    textAlign: 'center',
    marginBottom: 4,
  },
  subtitle: {
    color: arcane.text.muted,
    fontSize: 13,
    fontFamily: typography.fontFamily.body,
    textAlign: 'center',
    marginBottom: 16,
  },
  targetName: {
    color: '#d7b7ef',
    fontSize: 22,
    fontFamily: typography.fontFamily.display,
    textAlign: 'center',
    marginBottom: 4,
  },
  targetRole: {
    color: arcane.text.muted,
    fontSize: 14,
    fontFamily: typography.fontFamily.bodyMedium,
    textAlign: 'center',
    marginBottom: 20,
  },
  voteCount: {
    color: arcane.text.primary,
    fontSize: 15,
    fontFamily: typography.fontFamily.bodyBold,
    textAlign: 'center',
    marginBottom: 4,
  },
  threshold: {
    color: arcane.text.dead,
    fontSize: 12,
    fontFamily: typography.fontFamily.body,
    textAlign: 'center',
    marginBottom: 20,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  guiltyButton: {
    flex: 1,
    backgroundColor: arcane.action.bloodPressed,
    borderRadius: 4,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: arcane.action.blood,
  },
  guiltyButtonText: {
    color: arcane.action.bloodHighlight,
    fontSize: 16,
    fontFamily: typography.fontFamily.bodyBold,
  },
  innocentButton: {
    flex: 1,
    backgroundColor: arcane.accent.midnightInk,
    borderRadius: 4,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: arcane.accent.prussianBlue,
  },
  innocentButtonText: {
    color: arcane.accent.sapphireLens,
    fontSize: 16,
    fontFamily: typography.fontFamily.bodyBold,
  },
  votedText: {
    color: arcane.text.muted,
    fontSize: 15,
    fontFamily: typography.fontFamily.bodyMedium,
    textAlign: 'center',
    paddingVertical: 14,
  },
  resultPanel: {
    backgroundColor: arcane.surface.apparatus,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: arcane.border.brassDim,
    padding: 24,
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
  },
  resultTitle: {
    fontSize: 18,
    fontFamily: typography.fontFamily.display,
    textAlign: 'center',
    marginBottom: 8,
  },
  resultExiled: {
    color: arcane.action.bloodHighlight,
  },
  resultSurvived: {
    color: '#7dce82',
  },
  resultDetail: {
    color: arcane.text.muted,
    fontSize: 14,
    fontFamily: typography.fontFamily.body,
    textAlign: 'center',
    marginBottom: 16,
  },
  dismissButton: {
    backgroundColor: arcane.surface.ledger,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderWidth: 1,
    borderColor: arcane.border.parchment,
  },
  dismissText: {
    color: arcane.text.primary,
    fontSize: 14,
    fontFamily: typography.fontFamily.bodyBold,
  },
});
