import { colors, typography } from '@clocktower/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    zIndex: 10,
  },
  openingLabel: {
    color: colors.arcane.text.label,
    fontSize: 13,
    fontFamily: typography.fontFamily.bodyMedium,
    letterSpacing: 6,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  openingTitle: {
    color: colors.arcane.accent.sapphireLens,
    fontFamily: typography.fontFamily.display,
    fontSize: 24,
    fontWeight: '300',
    letterSpacing: 2,
    textAlign: 'center',
    marginBottom: 16,
  },
  openingDivider: {
    width: 60,
    height: 1,
    backgroundColor: colors.arcane.border.brassDim,
    marginBottom: 28,
  },
  flipContainer: {
    width: '100%',
    maxWidth: 340,
    position: 'relative',
  },
  flipFace: {
    width: '100%',
  },
  flipFaceBack: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  revealCard: {
    backgroundColor: colors.arcane.surface.ledger,
    borderRadius: 6,
    borderWidth: 1.5,
    padding: 22,
    width: '100%',
    overflow: 'hidden',
  },
  revealCardBack: {
    backgroundColor: colors.arcane.surface.apparatus,
  },
  shimmerContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 160,
    left: '50%',
    marginLeft: -80,
    zIndex: 1,
  },
  shimmerGradient: {
    flex: 1,
    transform: [{ skewX: '-15deg' }],
  },
  revealTeamLabel: {
    fontSize: 12,
    fontFamily: typography.fontFamily.bodyMedium,
    textTransform: 'uppercase',
    letterSpacing: 3,
    marginBottom: 6,
  },
  revealRoleName: {
    color: colors.arcane.text.strong,
    fontFamily: typography.fontFamily.display,
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 14,
    letterSpacing: 1,
  },
  revealDivider: {
    width: '100%',
    height: 1,
    backgroundColor: colors.arcane.border.brassDim,
    marginBottom: 14,
  },
  revealAbility: {
    color: colors.arcane.text.primary,
    fontSize: 14,
    lineHeight: 21,
  },
  evilInfoSection: {
    marginTop: 14,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  infoLabel: {
    color: colors.arcane.action.bloodHighlight,
    fontSize: 13,
    fontWeight: '600',
    width: 80,
  },
  infoValue: {
    color: colors.arcane.text.primary,
    fontSize: 13,
    flex: 1,
  },
  nightText: {
    color: colors.arcane.accent.sapphireLens,
    fontSize: 16,
    fontWeight: '300',
    letterSpacing: 1,
    marginTop: 32,
    textAlign: 'center',
  },
  dismissHint: {
    color: colors.arcane.text.dead,
    fontSize: 12,
    letterSpacing: 1,
    marginTop: 16,
  },

  // ── Back face styles ──
  backPatternContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'space-evenly',
    paddingVertical: 16,
    paddingHorizontal: 10,
  },
  backPatternRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 4,
  },
  backDiamond: {
    width: 14,
    height: 14,
    borderWidth: 1,
    borderColor: colors.arcane.accent.prussianBlue,
    transform: [{ rotate: '45deg' }],
  },
  backContent: {
    alignItems: 'center',
    paddingVertical: 20,
    zIndex: 2,
  },
  backTeamLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 4,
    color: colors.arcane.text.dead,
    marginBottom: 12,
  },
  backMysteryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  backMysteryLine: {
    width: 40,
    height: 1,
    backgroundColor: colors.arcane.border.brassDim,
  },
  backQuestionMark: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.arcane.accent.sapphireLens,
  },
  backDividerLine: {
    width: '60%',
    height: 1,
    backgroundColor: colors.arcane.border.brassDim,
    marginBottom: 16,
  },
  backPhrase: {
    color: colors.arcane.text.primary,
    fontSize: 14,
    fontStyle: 'italic',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  backSealContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  backSeal: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.arcane.border.brassDim,
    backgroundColor: colors.arcane.surface.ledger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backSealIcon: {
    color: colors.arcane.accent.sapphireLens,
    fontSize: 14,
  },
});
