import { colors } from '@clocktower/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  container: {
    alignItems: 'center',
    gap: 14,
    width: '100%',
    maxWidth: 520,
    maxHeight: '92%',
    padding: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(180,155,104,0.32)',
    backgroundColor: 'rgba(13,12,17,0.96)',
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    color: colors.text.primary,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  closeButton: {
    minWidth: 52,
    height: 34,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(180,155,104,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  closeText: {
    color: colors.text.secondary,
    fontSize: 13,
    fontWeight: '700',
  },
  ring: {
    position: 'relative',
  },
  voteOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  nominationArrow: {
    position: 'absolute',
    height: 3,
    borderRadius: 2,
    backgroundColor: '#d4a030',
    shadowColor: '#d4a030',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 6,
    transformOrigin: '0px 1.5px',
  },
  nominationArrowHead: {
    position: 'absolute',
    width: 0,
    height: 0,
    borderTopWidth: 6,
    borderBottomWidth: 6,
    borderLeftWidth: 12,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#d4a030',
  },
  token: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: colors.surface.elevated,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 5,
    paddingVertical: 5,
    zIndex: 2,
  },
  tokenMe: {
    backgroundColor: '#1e1c14',
    shadowColor: colors.phase.day,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  tokenPressed: {
    transform: [{ scale: 0.96 }],
  },
  nominatorToken: {
    borderColor: '#d4a030',
    backgroundColor: 'rgba(80,58,18,0.96)',
  },
  nomineeToken: {
    borderColor: '#c43c3c',
    backgroundColor: 'rgba(86,20,20,0.96)',
  },
  name: {
    color: '#b0aea8',
    fontWeight: '600',
    textAlign: 'center',
  },
  nameMe: {
    color: colors.text.primary,
  },
  roleNote: {
    color: '#e8d18a',
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 1,
  },
  deadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  dead: {
    color: colors.phase.vote,
    fontWeight: '700',
    marginTop: 1,
  },
  travellerTag: {
    color: '#a090c0',
    fontWeight: '600',
    marginTop: 1,
  },
  voteRightBadge: {
    position: 'absolute',
    left: '50%',
    bottom: -13,
    width: 58,
    height: 18,
    paddingHorizontal: 6,
    borderRadius: 9,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateX: -29 }],
  },
  voteRightAlive: {
    backgroundColor: 'rgba(54,108,68,0.9)',
    borderColor: 'rgba(104,191,119,0.65)',
  },
  voteRightGhost: {
    backgroundColor: 'rgba(28,71,112,0.95)',
    borderColor: 'rgba(90,160,208,0.85)',
  },
  voteRightSpent: {
    backgroundColor: 'rgba(58,58,66,0.92)',
    borderColor: 'rgba(132,132,144,0.35)',
  },
  voteRightText: {
    color: '#dce6dc',
    fontSize: 9,
    fontWeight: '800',
  },
  voteRightGhostText: {
    color: '#d8efff',
  },
  voteHandBadge: {
    position: 'absolute',
    top: -10,
    right: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voteHandRaised: {
    backgroundColor: 'rgba(130,26,26,0.95)',
    borderColor: '#e05050',
  },
  voteHandDown: {
    backgroundColor: 'rgba(25,26,32,0.95)',
    borderColor: '#6f7078',
  },
  voteHandImage: {
    width: 17,
    height: 17,
  },
  historyPanel: {
    width: '100%',
    gap: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderColor: 'rgba(180,155,104,0.18)',
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyTitle: {
    color: colors.text.secondary,
    fontSize: 13,
    fontWeight: '800',
  },
  clearVoteButton: {
    height: 28,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(180,155,104,0.25)',
    justifyContent: 'center',
  },
  clearVoteText: {
    color: colors.text.tertiary,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyHistory: {
    color: colors.text.tertiary,
    fontSize: 12,
  },
  historyList: {
    gap: 8,
    paddingRight: 4,
  },
  historyChip: {
    width: 138,
    minHeight: 62,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(180,155,104,0.22)',
    backgroundColor: 'rgba(255,255,255,0.035)',
    padding: 9,
    gap: 4,
  },
  historyChipSelected: {
    borderColor: '#d4a030',
    backgroundColor: 'rgba(90,63,14,0.38)',
  },
  historyChipRound: {
    color: '#d4a030',
    fontSize: 11,
    fontWeight: '900',
  },
  historyChipNames: {
    color: colors.text.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  historyChipVotes: {
    color: colors.text.tertiary,
    fontSize: 11,
    fontWeight: '700',
  },
  noteEditorOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 8,
    backgroundColor: 'rgba(0,0,0,0.68)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    zIndex: 10,
  },
  noteEditorPanel: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(180,155,104,0.35)',
    backgroundColor: '#16141c',
    padding: 16,
    gap: 10,
  },
  noteEditorName: {
    color: colors.text.primary,
    fontSize: 18,
    fontWeight: '800',
  },
  noteEditorLabel: {
    color: colors.text.secondary,
    fontSize: 12,
    fontWeight: '700',
  },
  noteInput: {
    height: 44,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(180,155,104,0.32)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: 12,
    color: colors.text.primary,
    fontSize: 15,
    fontWeight: '700',
  },
  noteEditorActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 4,
  },
  noteButton: {
    minWidth: 72,
    height: 38,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  noteButtonSecondary: {
    borderWidth: 1,
    borderColor: 'rgba(180,155,104,0.28)',
  },
  noteButtonSecondaryText: {
    color: colors.text.secondary,
    fontSize: 13,
    fontWeight: '800',
  },
  noteButtonPrimary: {
    backgroundColor: '#d4a030',
  },
  noteButtonPrimaryText: {
    color: '#17120a',
    fontSize: 13,
    fontWeight: '900',
  },
});
