import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  wrapper: {
    position: 'relative',
  },
  outerGlow: {
    position: 'absolute',
    top: -6,
    left: -6,
    right: -6,
    bottom: -6,
    borderRadius: 18,
    backgroundColor: '#4a5a8a',
  },
  card: {
    backgroundColor: '#16161a',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2a3050',
    padding: 20,
    overflow: 'hidden',
  },
  shimmerContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 180,
    left: '50%',
    marginLeft: -90,
  },
  shimmerGradient: {
    flex: 1,
    transform: [{ skewX: '-15deg' }],
  },
  veilPattern: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'space-evenly',
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  dotRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#6878a8',
  },
  content: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  teamLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 4,
    color: '#4a5070',
    marginBottom: 8,
  },
  mysteryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  mysteryLine: {
    width: 40,
    height: 1,
    backgroundColor: '#3a4060',
  },
  questionMark: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#5a6898',
  },
  divider: {
    width: '60%',
    height: 1,
    backgroundColor: '#242838',
    marginBottom: 16,
  },
  phrase: {
    color: '#7080b0',
    fontSize: 14,
    fontStyle: 'italic',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  sealContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  sealGlow: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#5a6898',
  },
  seal: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#3a4060',
    backgroundColor: '#1c1e28',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sealIcon: {
    color: '#5a6898',
    fontSize: 16,
  },
  hint: {
    color: '#3a3e4a',
    fontSize: 11,
    letterSpacing: 1,
  },
});
