import { StyleSheet } from 'react-native';

export const RING_SIZE = 240;
export const NODE_SIZE = 32;
export const CENTER = RING_SIZE / 2;
export const RADIUS = RING_SIZE / 2 - NODE_SIZE / 2 - 6;
export const HAND_LENGTH = RADIUS - 24;
export const TICK_COUNT = 60;
export const INNER_RING_RADIUS = RADIUS - 20;

export const COLORS = {
  brass: '#b8964e',
  brassLight: '#d4b06a',
  brassDark: '#8a6e38',
  blood: '#8b1a1a',
  bloodGlow: '#c43c3c',
  bloodDeep: '#5a0f0f',
  bone: '#d4cfc6',
  boneFaded: '#9a958c',
  iron: '#4a4a52',
  ironDark: '#2a2a30',
  midnight: '#0d0d12',
  midnightLight: '#16161e',
  active: '#e8c44a',
  activeGlow: '#f5d76e',
  activeDark: '#b8942a',
  guilty: '#c43c3c',
  innocent: '#6080b0',
};

export const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    marginVertical: 12,
  },
  outerGlow: {
    position: 'absolute',
    width: RING_SIZE + 30,
    height: RING_SIZE + 30,
    borderRadius: (RING_SIZE + 30) / 2,
    backgroundColor: `${COLORS.blood}15`,
    top: -3,
  },
  clockFace: {
    width: RING_SIZE,
    height: RING_SIZE,
    position: 'relative',
    backgroundColor: COLORS.midnight,
    borderRadius: RING_SIZE / 2,
  },
  outerRing: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: RING_SIZE / 2,
    borderWidth: 2.5,
    borderColor: COLORS.brassDark,
    shadowColor: COLORS.brass,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  innerRing: {
    position: 'absolute',
    left: CENTER - INNER_RING_RADIUS,
    top: CENTER - INNER_RING_RADIUS,
    width: INNER_RING_RADIUS * 2,
    height: INNER_RING_RADIUS * 2,
    borderRadius: INNER_RING_RADIUS,
    borderWidth: 0.8,
    borderColor: `${COLORS.brassDark}40`,
  },
  wedgeContainer: {
    position: 'absolute',
    left: CENTER - RADIUS * 0.55,
    top: CENTER - RADIUS,
    width: RADIUS * 1.1,
    height: RADIUS,
    transformOrigin: `${RADIUS * 0.55}px ${RADIUS}px`,
    zIndex: 4,
  },
  wedgeOuter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 0,
    height: 0,
    borderLeftWidth: RADIUS * 0.55,
    borderRightWidth: RADIUS * 0.55,
    borderBottomWidth: RADIUS,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: `${COLORS.active}08`,
  },
  wedgeInner: {
    position: 'absolute',
    bottom: 0,
    left: RADIUS * 0.55 - RADIUS * 0.22,
    width: 0,
    height: 0,
    borderLeftWidth: RADIUS * 0.22,
    borderRightWidth: RADIUS * 0.22,
    borderBottomWidth: RADIUS * 0.7,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: `${COLORS.active}12`,
  },
  handContainer: {
    position: 'absolute',
    left: CENTER - 4,
    top: CENTER - HAND_LENGTH,
    width: 8,
    height: HAND_LENGTH,
    alignItems: 'center',
    transformOrigin: `4px ${HAND_LENGTH}px`,
    zIndex: 10,
  },
  handGlow: {
    position: 'absolute',
    width: 8,
    borderRadius: 4,
  },
  hand: {
    position: 'absolute',
    width: 2.5,
    borderRadius: 1.5,
  },
  handTip: {
    position: 'absolute',
    top: -4,
    width: 0,
    height: 0,
    borderLeftWidth: 4,
    borderRightWidth: 4,
    borderBottomWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },
  centerOrnament: {
    position: 'absolute',
    left: CENTER - 8,
    top: CENTER - 8,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.ironDark,
    borderWidth: 1.5,
    borderColor: COLORS.brassDark,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 11,
  },
  centerDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.brass,
  },
  timerContainer: {
    position: 'absolute',
    left: CENTER - 18,
    top: CENTER + 18,
    width: 36,
    alignItems: 'center',
    zIndex: 12,
  },
  timerText: {
    color: COLORS.bone,
    fontSize: 18,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    textShadowColor: `${COLORS.brass}40`,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  node: {
    position: 'absolute',
    borderRadius: 16,
    backgroundColor: COLORS.midnightLight,
    borderWidth: 2,
    borderColor: COLORS.iron,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
  },
  deadNode: {
    opacity: 0.25,
  },
  nonVoterNode: {
    opacity: 0.3,
    borderColor: `${COLORS.iron}60`,
  },
  nomineeNode: {
    backgroundColor: COLORS.bloodDeep,
    borderColor: COLORS.bloodGlow,
    shadowColor: COLORS.bloodGlow,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 4,
  },
  activeNode: {
    backgroundColor: `${COLORS.activeDark}30`,
    borderColor: COLORS.active,
    shadowColor: COLORS.activeGlow,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 10,
    elevation: 6,
  },
  myNode: {
    borderColor: COLORS.brass,
  },
  guiltyNode: {
    borderColor: COLORS.guilty,
    backgroundColor: `${COLORS.guilty}20`,
  },
  innocentNode: {
    borderColor: COLORS.innocent,
    backgroundColor: `${COLORS.innocent}20`,
  },
  preselectedGuiltyNode: {
    borderColor: `${COLORS.guilty}70`,
    borderStyle: 'dashed',
  },
  preselectedInnocentNode: {
    borderColor: `${COLORS.innocent}70`,
    borderStyle: 'dashed',
  },
  pastNode: {
    opacity: 0.35,
  },
  nodeText: {
    color: COLORS.boneFaded,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  nomineeText: {
    color: COLORS.bloodGlow,
  },
  activeText: {
    color: COLORS.activeGlow,
  },
  myText: {
    color: COLORS.brassLight,
  },
  legend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    marginTop: 12,
    paddingHorizontal: 16,
  },
  legendText: {
    color: COLORS.boneFaded,
    fontSize: 11,
    letterSpacing: 0.3,
  },
});
