import { colors, typography } from '@clocktower/ui';
import { StyleSheet } from 'react-native';
import { VOTE_CONSENT_READY_ICON } from './VotePrompt.presentation';

const COLORS = {
  brass: colors.arcane.border.brass,
  brassLight: colors.arcane.text.label,
  brassDark: colors.arcane.border.brassDim,
  blood: colors.arcane.action.blood,
  bloodGlow: colors.arcane.action.bloodHighlight,
  bone: colors.arcane.text.strong,
  boneFaded: colors.arcane.text.muted,
  iron: '#4a4a52',
  midnight: colors.arcane.surface.base,
  midnightLight: colors.arcane.surface.apparatus,
};

export const styles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.midnightLight,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: COLORS.brassDark,
    padding: 20,
    shadowColor: COLORS.blood,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  label: {
    color: COLORS.bloodGlow,
    fontSize: 11,
    fontFamily: typography.fontFamily.bodyBold,
    textTransform: 'uppercase',
    letterSpacing: 4,
    marginBottom: 10,
    textShadowColor: `${COLORS.bloodGlow}40`,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  nominationInfo: {
    color: COLORS.boneFaded,
    fontSize: 15,
    fontFamily: typography.fontFamily.body,
    marginBottom: 4,
    lineHeight: 22,
  },
  playerNameHighlight: {
    color: COLORS.bone,
    fontFamily: typography.fontFamily.bodyBold,
    fontWeight: '800',
  },
  description: {
    color: '#d4a040',
    fontSize: 15,
    fontFamily: typography.fontFamily.bodyBold,
    fontWeight: '700',
    marginBottom: 16,
    textAlign: 'center',
  },
  votedContainer: {
    alignItems: 'center',
    paddingVertical: 14,
  },
  votedText: {
    color: COLORS.brass,
    fontSize: 16,
    fontFamily: typography.fontFamily.display,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  votedSubtext: {
    color: COLORS.boneFaded,
    fontSize: 13,
    fontFamily: typography.fontFamily.body,
    marginTop: 6,
    fontStyle: 'italic',
  },
  guiltyButton: {
    backgroundColor: '#1a1a20',
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#3a3a42',
  },
  guiltyButtonSelected: {
    backgroundColor: COLORS.blood,
    borderColor: '#e05050',
    shadowColor: '#e05050',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  guiltyText: {
    color: '#5c5a58',
    fontWeight: '900',
    fontSize: 17,
    letterSpacing: 0,
  },
  guiltyTextSelected: {
    color: colors.arcane.text.strong,
  },
  noSelectionHint: {
    color: COLORS.boneFaded,
    fontSize: 11,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  countdownContainer: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  countdownMessage: {
    color: COLORS.brass,
    fontSize: 16,
    fontFamily: typography.fontFamily.bodyBold,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 12,
  },
  countdownNumber: {
    color: COLORS.bloodGlow,
    fontSize: 48,
    fontFamily: typography.fontFamily.display,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    textShadowColor: `${COLORS.bloodGlow}60`,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  countdownHint: {
    color: COLORS.boneFaded,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 12,
    textAlign: 'center',
  },
  consentButton: {
    backgroundColor: '#1a1a20',
    borderRadius: 6,
    paddingVertical: 14,
    alignItems: 'center' as const,
    borderWidth: 1.5,
    borderColor: '#3a3a42',
    marginTop: 16,
    paddingHorizontal: 16,
  },
  consentButtonReady: {
    backgroundColor: '#1a4a2a',
    borderColor: '#3cb060',
    shadowColor: '#3cb060',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  consentText: {
    color: '#5c5a58',
    fontWeight: '800' as const,
    fontSize: 16,
    letterSpacing: 1,
  },
  consentTextReady: {
    color: colors.arcane.text.strong,
  },
  consentReadyIcon: {
    width: VOTE_CONSENT_READY_ICON.size,
    height: VOTE_CONSENT_READY_ICON.size,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#8fe0a8',
    backgroundColor: '#153d24',
    color: '#dfffe7',
    fontSize: 16,
    lineHeight: VOTE_CONSENT_READY_ICON.size - 2,
    textAlign: 'center',
    fontFamily: typography.fontFamily.bodyBold,
    fontWeight: '900',
  },
  voteButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  voteHandImage: {
    width: 34,
    height: 34,
  },
  consentCount: {
    color: COLORS.boneFaded,
    fontSize: 12,
    textAlign: 'center' as const,
    marginTop: 8,
  },
});
