import { StyleSheet } from 'react-native';

const COLORS = {
  brass: '#b8964e',
  brassLight: '#d4b06a',
  brassDark: '#8a6e38',
  blood: '#8b1a1a',
  bloodGlow: '#c43c3c',
  bone: '#d4cfc6',
  boneFaded: '#9a958c',
  iron: '#4a4a52',
  midnight: '#0d0d12',
  midnightLight: '#14141c',
};

export const styles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.midnightLight,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.brassDark,
    padding: 20,
    shadowColor: COLORS.blood,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  label: {
    color: COLORS.bloodGlow,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 4,
    marginBottom: 10,
    textShadowColor: `${COLORS.bloodGlow}40`,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  nominationInfo: {
    color: COLORS.boneFaded,
    fontSize: 15,
    marginBottom: 4,
    lineHeight: 22,
  },
  playerNameHighlight: {
    color: COLORS.bone,
    fontWeight: '800',
  },
  description: {
    color: '#d4a040',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 16,
    textAlign: 'center',
  },
  votedContainer: {
    alignItems: 'center',
    paddingVertical: 14,
  },
  votedText: {
    color: COLORS.brass,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  votedSubtext: {
    color: COLORS.boneFaded,
    fontSize: 13,
    marginTop: 6,
    fontStyle: 'italic',
  },
  guiltyButton: {
    backgroundColor: '#1a1a20',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#3a3a42',
  },
  guiltyButtonSelected: {
    backgroundColor: COLORS.blood,
    borderColor: '#e05050',
    shadowColor: '#e05050',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  guiltyText: {
    color: '#5c5a58',
    fontWeight: '900',
    fontSize: 18,
    letterSpacing: 3,
  },
  guiltyTextSelected: {
    color: '#ffffff',
  },
  noSelectionHint: {
    color: COLORS.boneFaded,
    fontSize: 11,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  countdownContainer: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  countdownMessage: {
    color: COLORS.brass,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 12,
  },
  countdownNumber: {
    color: COLORS.bloodGlow,
    fontSize: 48,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    textShadowColor: `${COLORS.bloodGlow}60`,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  countdownHint: {
    color: COLORS.boneFaded,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 12,
    textAlign: 'center',
  },
});
